Repository kichel98/BlankietyGalantow, pull requests merged in 2020-06, with the labels that each got.

#98 Bug fix
  blankiety_galantow/resources/game/js/websocket_connect.js
Labels: bug, frontend

#99 Tooltip jako opis trybu gry
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/index.html
Labels: frontend, funkcjonalność

#102 Klasa RoomSettings
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/room_settings.py
  blankiety_galantow/core/server.py
Labels: backend, funkcjonalność

#106 Feat/password protection
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/room_settings.py
  blankiety_galantow/core/server.py
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
Labels: backend, frontend, funkcjonalność

#111 Favicon
  blankiety_galantow/app.py
  blankiety_galantow/resources/assets/favicon.ico
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/index.html
Labels: frontend

#112 Bugfix Timer CancelledError
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/utils/timer.py
Labels: backend, bug

#113 Poprawki do wyglądu strony głównej
  blankiety_galantow/resources/assets/logo.png
  blankiety_galantow/resources/css/main.css
  blankiety_galantow/resources/index.html
  blankiety_galantow/resources/js/components.js
Labels: frontend

#115 Graphics
  blankiety_galantow/resources/assets/error_graphic.png
  blankiety_galantow/resources/assets/password_graphic.png
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
Labels: frontend

#116 Feat/delete room after last player left
  blankiety_galantow/app.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/server.py
Labels: backend, pilne

#119 Feat/game pause
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/room_settings.py
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/vendor/fontello/config.json
  blankiety_galantow/resources/vendor/fontello/css/fontello-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-embedded.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7.css
  blankiety_galantow/resources/vendor/fontello/css/fontello.css
  blankiety_galantow/resources/vendor/fontello/demo.html
  blankiety_galantow/resources/vendor/fontello/font/fontello.eot
  blankiety_galantow/resources/vendor/fontello/font/fontello.svg
  blankiety_galantow/resources/vendor/fontello/font/fontello.ttf
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff2
Labels: backend, frontend, funkcjonalność

#120 Red lock for room with password
  blankiety_galantow/core/server.py
  blankiety_galantow/resources/index.html
  blankiety_galantow/resources/js/components.js
Labels: backend, frontend, funkcjonalność

#123 Bugfix disabling password
  blankiety_galantow/resources/game/js/main.js
Labels: bug, frontend

#126 Feat/kick rework
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/kick_exception.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
Labels: backend, bug

#125 BugFix with different time for different players
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/js/main.js
Labels: backend, bug, frontend
