Repository kichel98/BlankietyGalantow, pull requests merged in 2020-05, with the labels that each got.

#1 Dodanie specyfikacji projektu
  docs/README.md
Labels: dokumentacja

#9 Podstawowa obsługa statycznych plików przez REST API
  blankiety_galantow/app.py
  blankiety_galantow/resources/css/main.css
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/index.html
  blankiety_galantow/resources/js/components.js
  blankiety_galantow/resources/js/main.js
  blankiety_galantow/resources/vendor/fontello/LICENSE.txt
  blankiety_galantow/resources/vendor/fontello/README.txt
  blankiety_galantow/resources/vendor/fontello/config.json
  blankiety_galantow/resources/vendor/fontello/css/animation.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-embedded.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7.css
  blankiety_galantow/resources/vendor/fontello/css/fontello.css
  blankiety_galantow/resources/vendor/fontello/demo.html
  blankiety_galantow/resources/vendor/fontello/font/fontello.eot
  blankiety_galantow/resources/vendor/fontello/font/fontello.svg
  blankiety_galantow/resources/vendor/fontello/font/fontello.ttf
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff2
  blankiety_galantow/resources/vendor/hover/hover-min.css
  blankiety_galantow/resources/vendor/hover/hover.css
  blankiety_galantow/resources/vendor/hover/hover.css.map
  blankiety_galantow/resources/vendor/vue/vue-dev.js
  blankiety_galantow/resources/vendor/vue/vue.js
  blankiety_galantow/resources/vendor/w3css/w3.css
  blankiety_galantow/routers.py
  requirements.txt
Labels: funkcjonalność

#10 Dodano opis mechaniki rozgrywki.
  .gitignore
  docs/README.md
Labels: dokumentacja

#15 Feat/websockets connect
  blankiety_galantow/app.py
  blankiety_galantow/core/__init__.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/server.py
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/game/js/websocket_connect.js
  blankiety_galantow/resources/index.html
  blankiety_galantow/resources/js/components.js
  blankiety_galantow/resources/js/main.js
  blankiety_galantow/routers.py
  docs/prototype/game-vue/index.html
  docs/prototype/game-vue/js/main.js
  docs/prototype/game-vue/js/websocket_connect.js
  docs/prototype/servers-vue/index.html
  docs/prototype/servers-vue/js/main.js
Labels: funkcjonalność

#17 Feat/servers endpoint draft
  blankiety_galantow/app.py
  blankiety_galantow/core/helpers.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/server.py
  blankiety_galantow/resources/game/js/websocket_connect.js
  blankiety_galantow/routers.py
Labels: funkcjonalność

#22 Propozycja wiadomości przesyłanych przez sockety
  docs/COMMUNICATION.md
Labels: dokumentacja

#23 Local Storage support
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/game/js/websocket_connect.js
  blankiety_galantow/resources/js/main.js
Labels: backend, frontend, funkcjonalność

#29 Update COMMUNICATION.md
  docs/COMMUNICATION.md
Labels: dokumentacja

#24 Feat/run arguments
  README.md
  blankiety_galantow/app.py
  blankiety_galantow/resources/game/js/websocket_connect.js
Labels: backend, funkcjonalność

#27 Feat/card select
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/vendor/fontello/LICENSE.txt
  blankiety_galantow/resources/vendor/fontello/config.json
  blankiety_galantow/resources/vendor/fontello/css/fontello-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-embedded.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7.css
  blankiety_galantow/resources/vendor/fontello/css/fontello.css
  blankiety_galantow/resources/vendor/fontello/demo.html
  blankiety_galantow/resources/vendor/fontello/font/fontello.eot
  blankiety_galantow/resources/vendor/fontello/font/fontello.svg
  blankiety_galantow/resources/vendor/fontello/font/fontello.ttf
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff2
Labels: frontend, funkcjonalność

#33 Fixed room list view on mobile
  blankiety_galantow/resources/css/main.css
Labels: bug, frontend

#35 Refaktoryzacja kodu feat/card-master-view
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
Labels: backend, dokumentacja, pilne

#36 Dodano informacje o postępach z zeszłego tygodnia.
  updates.txt
Labels: dokumentacja

#31 Feat/card master view
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/resources/vendor/fontello/config.json
  blankiety_galantow/resources/vendor/fontello/css/fontello-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-embedded.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7.css
  blankiety_galantow/resources/vendor/fontello/css/fontello.css
  blankiety_galantow/resources/vendor/fontello/demo.html
  blankiety_galantow/resources/vendor/fontello/font/fontello.eot
  blankiety_galantow/resources/vendor/fontello/font/fontello.svg
  blankiety_galantow/resources/vendor/fontello/font/fontello.ttf
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff2
Labels: frontend, funkcjonalność

#39 Feat/create server
  blankiety_galantow/app.py
  blankiety_galantow/core/server.py
  blankiety_galantow/resources/index.html
  blankiety_galantow/resources/js/components.js
  blankiety_galantow/resources/js/main.js
  blankiety_galantow/resources/vendor/fontello/config.json
  blankiety_galantow/resources/vendor/fontello/css/fontello-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-embedded.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7-codes.css
  blankiety_galantow/resources/vendor/fontello/css/fontello-ie7.css
  blankiety_galantow/resources/vendor/fontello/css/fontello.css
  blankiety_galantow/resources/vendor/fontello/demo.html
  blankiety_galantow/resources/vendor/fontello/font/fontello.eot
  blankiety_galantow/resources/vendor/fontello/font/fontello.svg
  blankiety_galantow/resources/vendor/fontello/font/fontello.ttf
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff
  blankiety_galantow/resources/vendor/fontello/font/fontello.woff2
  blankiety_galantow/routers.py
Labels: backend, frontend, funkcjonalność

#41 Repaired incorrectly closed html tags
  blankiety_galantow/resources/game/js/components.js
Labels: bug

#38 Dodano klasę Deck i mockupy csv treścią kart w resources.
  blankiety_galantow/core/deck.py
  blankiety_galantow/resources/game/decks/classic_black.csv
  blankiety_galantow/resources/game/decks/classic_white.csv
Labels: backend, funkcjonalność

#42 Feat/send players list
  blankiety_galantow/core/helpers.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/routers.py
Labels: backend, funkcjonalność, pilne

#46 Feat/game master
  blankiety_galantow/core/deck.py
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/utils/__init__.py
  blankiety_galantow/core/utils/observable_list.py
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
Labels: backend, frontend, funkcjonalność

#47 Wypisywanie logów, usprawnienie debugowania
  blankiety_galantow/app.py
  blankiety_galantow/core/deck.py
  blankiety_galantow/core/room.py
  blankiety_galantow/routers.py
Labels: backend, funkcjonalność

#48 Feat/loader
  blankiety_galantow/core/deck.py
  blankiety_galantow/resources/game/css/loader.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
Labels: frontend, funkcjonalność

#53 change the visibility of the settings buttons for non-admins #34
  blankiety_galantow/resources/game/index.html
Labels: frontend, funkcjonalność

#54 Feat/card select backend
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/kick_exception.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
Labels: backend, funkcjonalność

#55 Added game app loader
  blankiety_galantow/resources/game/css/loader.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
  blankiety_galantow/resources/game/js/main.js
Labels: frontend, funkcjonalność

#59 Separated Chat module from Room
  blankiety_galantow/core/chat.py
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/room.py
Labels: backend, funkcjonalność

#61 Move player hand from GameMaster to Player
  blankiety_galantow/core/deck.py
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/player.py
Labels: backend

#66 Selecting winning card backend
  blankiety_galantow/core/deck.py
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/js/main.js
  blankiety_galantow/routers.py
Labels: backend, frontend, funkcjonalność

#67 Added closing/opening room functionality
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/css/loader.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
Labels: backend, frontend, funkcjonalność

#79 Feat/table transitions
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
Labels: frontend, funkcjonalność, niski priorytet

#80 Bugfix/multiple bugfixes
  blankiety_galantow/core/deck.py
  blankiety_galantow/core/game_master.py
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/components.js
Labels: backend, bug, frontend

#84 Feat/timer
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/game_state.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/core/utils/timer.py
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
  requirements.txt
Labels: backend, frontend, funkcjonalność

#89 Custom cards functionality
  blankiety_galantow/core/game_master.py
  blankiety_galantow/core/player.py
  blankiety_galantow/core/room.py
  blankiety_galantow/resources/game/css/main.css
  blankiety_galantow/resources/game/index.html
  blankiety_galantow/resources/game/js/main.js
Labels: backend, frontend, funkcjonalność, niski priorytet
